### PR TITLE
Remove reference to terminal tab

### PR DESCRIPTION
**Pull request by gdw2vs**
This option is now(?) gone

:memo: Description

:white_check_mark: Checklist

- [ ] Commits should be cryptographically signed (SSH or GPG)

## Practicalli Guidelines

Please follow these guidelines when submitting a pull request

- refer to all relevant issues, using `#` followed by the issue number (or paste full link to the issue)
- PR should contain the smallest possible change
- PR should contain a very specific change
- PR should contain only a single commit (squash your commits locally if required)
- Avoid multiple changes across multiple files (raise an issue so we can discuss)
- Avoid a long list of spelling or grammar corrections.  These take too long to review and cherry pick.

## Submitting articles

[Create an issue using the article template](https://github.com/practicalli/blog-content/issues/new?assignees=&labels=article&template=article.md&title=Suggested+article+title),
providing as much detail as possible.

## Website design

Suggestions about website design changes are most welcome, especially in terms of usability and accessibility.

Please raise an issue so we can discuss changes first, especially changes related to aesthetics.

## Review process

All pull requests are reviewed by @practicalli-johnny and feedback provided, usually the same day but please be patient.

### CODE REVIEW

**Comment by gdw2vs** [comment]
Please confirm on your end, but if this option was here at one point, i think it's now gone.

**Comment by gdw2vs** [comment]
Looks like `<leader> t t` is supposed to open up `btm`, which I don't have installed, so I don't see the shortcut.  If that's the case, we need to update the docs, not remove them...

**Comment by practicalli-johnny** [comment]
Yes, its a change in AstroNvim 4 it seems.  I'll update the page later today.  Thank you.

**Comment by practicalli-johnny** [comment]
The underlying command has been added to the Terminal page, replacing the previous key mapping.  I'll consider adding a new key mapping in `lua/plugins/user-practicalli.lua`

**Pull request closed without merging**
